import pytest
from csirtg_indicator.format.zbindrpzip import BindRPZIP, get_lines
from csirtg_indicator import Indicator
from pprint import pprint
import re

@pytest.fixture
def indicator():
    i = {
        'indicator': "2001:DB8::/32",
        'provider': "me.com",
        'tlp': "amber",
        'confidence': "8",
        'reporttime': '2022-01-01T00:00:00Z',
        'itype': 'ipv6'
    }
    return Indicator(**i)


def test_format_bindrpzip(indicator):
    data = [indicator]
    text = str(BindRPZIP(data))

    assert re.findall(r'^;;; generated by: csirtg-indicator at \S+', text)
    assert re.findall(r'@\s+IN\s+NS\s+localhost.', text)
    assert re.findall(r'32.zz.db8.2001.rpz-ip\s+CNAME .', text)


def test_format_bindrpzip2(indicator):

    data = [indicator, indicator]
    n = list(get_lines(data))
    assert len(n) > 0

if __name__ == '__main__':
    test_format_bindrpzip()
